export const errorEN: LanguageKeyValueMap = {
	// AnalysisControllerException
	error_98000: 'Unexpected exception: {{exmsg}}',
	error_98001: 'Bad request body.',
	error_98002: 'Invalid DataSourceInfo.',
	error_98003: 'Failed to get information of provider \'{{provider}}\'. {{exmsg}}',
	error_98004: 'The document was not found or you have not enough permission to access it.',
	error_98005: 'UPDATE permission required.',
	error_98006: 'Current model does not match the database schema.',
	error_98007: 'Failed to connect to the database.',
	error_98008: 'Failed to get tables.',
	error_98009: 'Failed to get columns.',
	error_98010: 'Failed to create data model.',
	error_98011: 'Failed to validate the entity.',
	error_98012: 'Failed to validate the attribute.',
	error_98013: 'Failed to validate the data model.',
	error_98014: 'Failed to save the data model.',
	error_98015: 'Failed to update the data model.',
	error_98016: 'Failed to load the data model.',
	error_98017: 'Failed to preview the entity.',
	error_98018: 'Failed to get databases.',
	error_98019: 'The number of selected tables/views is greater than the maximum limit: {{limit}}.',
	error_98020: 'Can not get the schema of table {{binding}}.',
	error_98021: 'Can not get the information of column {{column}} on the table {{table}}.',
	error_98022: 'Failed to validate the relation.',
	error_98023: 'Failed to validate the security filter(s), please create a custom attribute and use the CAST function to convert the attribute value into a compatible datatype.',

	// DataProviderServiceException
	error_93001: 'User context values required by connection string are missing on current user\'s scope. Context properties: {{contexts}}',
	error_93002: '\'Database\' is not configured on connection.',
	error_93003: 'Provider {{provider}} not registered.',
	error_93004: 'Provider {{provider}} does not support DirectQuery data analysis feature.',
	error_93005: 'Provider is not assigned.',
	error_93006: 'Failed to create connection.',
	error_93007: 'Failed to open connection.',
	error_93008: 'Failed to get the columns.',
	error_93009: 'Failed to get the foreign keys.',
	error_93010: 'Failed to get tables.',
	error_93011: 'Failed to get views.',
	error_93012: 'Failed to test connection.',
	error_93013: 'Failed to execute SQL.',
	error_93014: 'Failed to read SQL data.',
	error_93015: 'Failed to get databases.',

	// IntegrityValidationException
	error_96001: 'Id and name are missing on an entity.',
	error_96002: 'Id is missing on entity \'{{name}}\'.',
	error_96003: 'Name is missing on entity {{id}}.',
	error_96004: 'Duplicated name \'{{name}}\' was found on entities.',
	error_96005: 'Duplicated id {{id}} was found on more than one model items.',
	error_96006: 'Id and name are missing on a relation.',
	error_96007: 'Id is missing on relation \'{{name}}\'.',
	error_96008: 'Name is missing on relation {{id}}.',
	error_96009: 'Duplicated name \'{{name}}\' was found on relations {{ids}}.',
	error_96010: 'Id and name are missing on an attribute of entity \'{{entityname}}\'.',
	error_96011: 'Id is missing on attribute \'{{name}}\' of entity \'{{entityname}}\'.',
	error_96012: 'Name is missing on attribute {{id}} of entity \'{{entityname}}\'.',
	error_96013: 'Duplicated name \'{{name}}\' was found on attributes {{ids}} of entity \'{{entityname}}\'.',
	error_96014: 'Model contains no entities.',
	error_96015: 'Entity \'{{name}}\' contains no attributes.',
	error_96018: 'Source attribute(s) of relation \'{{name}}\' are missing.',
	error_96019: 'Target attribute(s) of relation \'{{name}}\' are missing.',
	error_96020: 'Source attribute \'{{att}}\' of relation \'{{name}}\' is illegal.',
	error_96021: 'Target attribute \'{{att}}\' of relation \'{{name}}\' is illegal.',
	error_96022: 'One or more source attributes and target attributes of relation \'{{name}}\' are the same.',
	error_96024: 'DataAnalysisModel is null.',
	error_96025: 'Model is null.',
	error_96026: 'DataSource is not configured.',
	error_96027: 'ConnectionString of the dataSource is not configured.',
	error_96028: 'Provider of the dataSource is not configured.',
	error_96029: 'Referenced DSC document id of the dataSource is not configured.',
	error_96030: 'Datasource type is unrecognizable.',
	error_96031: 'Bi-direction cross filtering must be enabled on the one-to-one relation \'{{name}}\'.',
	error_96032: 'Internal error.',
	error_96033: 'There are multiple direct relations between entity \'{{name1}}\' and entity \'{{name2}}\'.',
	error_96034: 'Binding is not configured on entity \'{{name}}\'.',
	error_96035: 'Binding is not configured on attribute \'{{name}}\' of entity \'{{entityname}}\'.',
	error_96036: 'There are multiple paths between entity \'{{name1}}\' and entity \'{{name2}}\'. Path1 is \'{{path1}}\'. Path2 is \'{{path2}}\'.',
	error_96037: 'Count of source and target attributes on relation \'{{name}}\' does not match.',
	error_96038: 'Source attributes on relation \'{{name}}\' do not belong to the same entity.',
	error_96039: 'Target attributes on relation \'{{name}}\' do not belong to the same entity.',
	error_96040: 'Failed to deserialize: Attribute with id \'{{attid}}\' is not defined.',
	error_96041: 'Source attribute is not configured in security filter \'{{filtername}}\'.',
	error_96042: 'Source attribute \'{{attributename}}\' in security filter \'{{filtername}}\' does not belong to current data model.',
	error_96043: 'Context property name is not configured in security filter \'{{filtername}}\'.',
	error_96044: 'The IsUnique flag required to be true on the attribute \'{{attribute}}\' that is used as the relational field of the \'1\' side entity \'{{entity}}\' in the relation \'{{relation}}\'.',
	error_96045: 'The IsUnique flag required to be true on both the \'{{attribute1}}\' of the entity \'{{entity1}}\' and the \'{{attribute2}}\' of the entity \'{{entity2}}\' in the one to one relation \'{{relation}}\'.',

	// inner exception
	error_inner: 'internal error: {{msg}}',

	// rename graphql
	err_20001: '{{parameter}} is a required parameter.',
	err_20002: 'Document "{{newName}}" already exists.',
	err_20006: 'Document "{{documentProperty}}" is not found.',
	err_20009: 'The document cannot be renamed. You do not have sufficient permissions on this document to perform the action. Please contact your administrator in case you feel this is incorrect.',
	err_20014: 'Invalid document name. Document name can not be empty and please do not use restricted symbols < > \\ : ? * / | \" and do not use . (dot) as the first symbol in the document name.',

	// JDBC proxy error message
	'err_5001': 'Can not connect to JDBC proxy.',

	// AutoModelBuilderException
	error_96201: 'DatasourceSchemaResolver is not provided.',
	error_96202: 'DatasourceCharacterResolver is not provided.',
	error_96203: 'Datasource definition is missing.',
	error_96204: 'One or more empty table names found.',
	error_96205: "One or more empty column names found in table '{{table}}'.",
	error_96206: "DbDataType is missing on column '{{column}}' of table '{{table}}'.",
	error_96207: 'Failed to resolve datasource schema.',
	error_96208: "Failed to infer logical data type from database data type '{{dbdatatype}}'.",
	error_96209: 'One ore more empty relation names found.',
	error_96210: "Failed to find referencing column of relation '{{relation}}'.",
	error_96211: "Failed to find referenced column of relation '{{relation}}'.",
	error_96212: 'Failed to resolve datasource character.',

	// LocalEntity
	error_98024: 'Fail to validate the local entity.',
	error_98025: 'The {{column}} column type error.',
	error_98026: 'Can not to get local entity Generator.',

	// Entity Parameter
	error_98027: 'Failed to validate the entity parameter.',
	error_98028: 'Not support the entity with Custom SQL.',

	// localEntityGraphql
	error_98037: 'Excel connection failed to open.',
	error_60200: 'A non-empty row collection is required for column data type inference.',
	error_60201: 'Excel sheet should not be empty.',
	error_60009: 'No available sheets found in Excel file.',
	error_60008: 'This is an encrypted file, please provide the password.',

	// GetData
	error_98029: 'Failed to open the document. It may be due to multiple people editing the current document at the same time, or there is a problem with the cache database.',
	error_98030: 'Failed to check the edit lock in cache mode.',
	error_98031: 'Failed to get data.',
	error_98032: 'Failed to select one available cache node.',

	error_200001: '"{{value}}" in {{row}} row and {{column}} column of the {{entityName}} table cannot be converted from a {{originalType}} type to a {{conversionType}} type.',
	error_200002: '{{logicalDataType}} type is not supported.',
	error_200003: 'Data is not exist or invalid.',
	error_200004: 'Access denied to "{{directory}}"',
	error_200005: 'Failed to convert value in {{row}} row to target data type.',
	error_200006: 'Unknown runtime errors occurred.',
	error_200007: 'Failed to generate binary files.',
	error_200008: 'Model documentId is empty.',
	error_200009: 'Cannot get the cache node.',
	error_200010: 'Failed to transport files.',
	error_200011: 'Failed to generate cache.',
	error_200012: 'Failed to generate cache.',
	error_200013: 'Failed to generate cache.',
	error_200015: 'Failed to execute SQL initialization script in cache.',

	error_100000001: 'Failed to get cache storage node.',
	error_100000002: 'Data is found in inactive cache node.',
	error_100000003: 'Data is not found in active cache node.',
	error_100000004: 'Data is not exist.',
	error_100000005: 'Operation is canceled in client.',
	error_100000006: 'Client internal error.',
	error_100000007: 'System is shutdown.',
	error_100000008: 'Cache node is offline.',
	error_100000009: 'Failed to confirm lock.',
	error_100000010: 'Failed to update cache lock.',
	error_200000001: 'Client is unavailable.',
	error_200000002: 'Cache storage is not start.',
	error_200000003: 'Cache storage error.',
	error_200000004: 'Server operation is canceled.',
	error_200000005: 'Cannot acquire lock.',
	error_200000006: 'Server internal error.',
	error_200000007: 'Failed to release lock.',
	error_200000008: 'Failed to check lock.',

	error_98036: 'Failed to validate data sources.',
	err_100018: 'Document not found.',
	error_98038: 'The cache is being rebuilt and the document cannot be edited.',
	error_98039: 'Failed to convert a value of the column {{ columnName }} to data type {{ convertedType }} .',
};